Controllers/DocumentsController.cs
using RecruitmentPortal.Models;
using RecruitmentPortal.Services.Entities;
using RecruitmentPortal.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecruitmentPortal.Controllers
{
    public class DocumentsController : Controller
    {
        ApplicationDbContext _db;
        IDocuments _iDocuments;
        public DocumentsController(IDocuments iDocuments, ApplicationDbContext db)
        {
            _iDocuments = iDocuments;
            _db = db;
        }
        // GET: Documents
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult CreateDocument()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDocument(Document document, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Method 1: Get file details from current request
                    if(Request.Files.Count > 0)
                    {
                        var uploadfile = Request.Files[0];
                        if(uploadfile != null && uploadfile.ContentLength > 0)
                        {
                            _iDocuments.InsertDoc(document, uploadfile);
                        }
                    }
                    ViewBag.Status = "Uploaded Successfully";
                }
                catch (Exception)
                {
                    ViewBag.Status = "Error while uploading file";
                }           
            }
            return View();
        }
    }
}

Views/Documents/CreateDocument.cshtml
@model RecruitmentPortal.Services.Entities.Document
@{
    ViewBag.Title = "CreateDocument";
}

<section class="mini-padding create-category">
    <div class="container">
        <div class="row mb-4">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="page-header">
                    <div class="page-breadcrumb">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#" class="breadcrumb-link">Recruitment Portal</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Create Document</li>
                                <li class="breadcrumb-item active" aria-current="page"><a href="/Category/Index">Back to List</a></li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center align-items-center">
            <div class="col-md-7">
                <div class="card">
                    <h5 class="card-header">Validation State</h5>
                    <div class="card-body px-4 py-3">
                        @using (Html.BeginForm("CreateDocument", "Documents", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                        <div>

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "" })

                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "" })

                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.file, htmlAttributes: new { @class = "" })
                                @Html.EditorFor(model => model.file, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                            </div>

                            <div class="form-group">

                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Documents/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>