Controllers/HomeController.cs
using RecruitmentPortal.Services.Interfaces;
using RecruitmentPortal.Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecruitmentPortal.Controllers
{
    public class HomeController : Controller
    {
        IJobs _iJobs; ICategory _iCategory;
        public HomeController(IJobs iJobs, ICategory iCategory)
        {
            _iJobs = iJobs;
            _iCategory = iCategory;
        }
        public ActionResult Index()
        {
            var model = new IndexViewModel
            {
                Jobs = _iJobs.LimitedJobs(),
                Categories = _iCategory.GetCategories()
            };
            /*var jobs = _iJobs.LimitedJobs();*/
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
       
    }
}

Controllers/JobsController.cs
using RecruitmentPortal.Services.Entities;
using RecruitmentPortal.Services.Interfaces;
using RecruitmentPortal.Services.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RecruitmentPortal.Controllers
{
    public class JobsController : Controller
    {
        IJobs _iJobs; ICategory _iCategory;
        public JobsController(IJobs iJobs, ICategory iCategory)
        {
            _iJobs = iJobs;
            _iCategory = iCategory;
        }
        // GET: Jobs
        public ActionResult Index()
        {
            var jobs = _iJobs.GetJobs();
            return View(jobs);
        }
        [Authorize (Roles ="APPLICANT")]
        public ActionResult AllJobs()
        {
            var jobs = _iJobs.GetJobs();
            return View(jobs);
        }
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(_iJobs.Any(), "Id", "CategoryName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Jobs jobs)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.CategoryID = new SelectList(_iJobs.Any(), "Id", "CategoryName", jobs.CategoryID);
                return View(jobs);
            }
                _iJobs.InsertJobs(jobs);
                return RedirectToAction("Index");
        }
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == 0)
                {
                    ViewBag.Error = "Invalid Request sent, Try Again";
                    return View();
                }
                var product = _iJobs.GetJobsById(id.Value);
                return View(product);
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"An Error Occured: {ex.Message.ToString()}";
            }
            return View();
        }
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == 0)
                {
                    ViewBag.Error = "Invalid Request sent, Try Again";
                    return View();
                }
                var product = _iJobs.GetJobsById(id.Value);
                return View(product);
            }
            catch (Exception ex)
            {
                ViewBag.Error = $"An Error Occured: {ex.Message.ToString()}";
            }
            return View();
        }
        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _iJobs.DeleteJobsById(id);
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Jobs jobs = _iJobs.GetJobsById(id.Value);

            if (jobs == null)
                return HttpNotFound();

            ViewBag.CategoryID = new SelectList(_iJobs.Any(), "Id", "CategoryName", jobs.CategoryID);
            return View(jobs);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Jobs jobs)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.CategoryID = new SelectList(_iJobs.Any(), "Id", "CategoryName", jobs.CategoryID);
                return View(jobs);
            }
            _iJobs.UpdateJobs(jobs);
            return RedirectToAction("Index");
        }
        /*public ActionResult SearchResult(string keyword, string location, string category)
        {
            var model = new IndexViewModel
            {
                Jobs = _iJobs.SearchResult(keyword, location, category),
                Categories = _iCategory.GetCategories()
            };

            return View(model);
        }*/
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model RecruitmentPortal.Services.ViewModels.IndexViewModel
@{
    ViewBag.Title = "Home Page";
}
<section class="banner padding">
    <div class="container">
        <div class="row justify-content-center align-items-center text-center mb-4">
            <div class="col">
                <div class="section-heading mx-auto mb-4">
                    <h2 class="text-white">Find All Jobs</h2>
                    <p class="text-white">Find Jobs, Employment & Best Career Opportunities</p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center align-content-center">
            <div class="col-10 mx-auto">
                <form class="banner-form">
                    @using (Html.BeginForm("SearchResult", "Jobs", FormMethod.Post))
                    {
                        <div class="form-row">
                            <div class="col">
                                <input type="text" class="form-control" placeholder="Job Title or Keyword">
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" placeholder="Location">
                            </div>
                            <div class="col">
                                <select class="custom-select form-control">
                                    <option value="">----Select Category----</option>
                                    @foreach (var item in Model.Categories)
                                    {
                                        <option value="@item.Id">@item.CategoryName</option>
                                    }
                                </select>
                            </div>

                            <div class="col">
                                <button class="btn btn-primary btn-block form-control search-btn" type="submit">Search</button>
                            </div>
                        </div>
                    }
                </form>
            </div>
        </div>


    </div>
</section>
<section class="browse-jobs padding">
    <div class="container">
        <div class="row justify-content-center align-items-center text-center mb-4">
            <div class="col">
                <div class="section-heading mx-auto mb-4">
                    <p>New & Trending Jobs</p>
                    <h2>Most Popular & Trending Jobs</h2>
                </div>
            </div>
        </div>
        <div class="row justify-content-center align-items-center text-center mb-5">
            <div class="col-md-3 col-sm-6 col-xs-6 mt-3">
                <div class="job-wrap">
                    <div class="job-icon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <div class="job-title mt-2">
                        <a class="#">IT Engineer</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6 mt-3">
                <div class="job-wrap">
                    <div class="job-icon">
                        <i class="fa fa-suitcase"></i>
                    </div>
                    <div class="job-title mt-2">
                        <a class="#">Management</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6 mt-3">
                <div class="job-wrap">
                    <div class="job-icon">
                        <i class="fa fa-tachometer-alt"></i>
                    </div>
                    <div class="job-title mt-2">
                        <a class="#">
                            Digital & Creative
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6 mt-3">
                <div class="job-wrap">
                    <div class="job-icon">
                        <i class="fa fa-money-bill"></i>
                    </div>
                    <div class="job-title mt-2">
                        <a class="#">
                            Accounting
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6 mt-3">
                <div class="job-wrap">
                    <div class="job-icon">
                        <i class="fa fa-chart-line"></i>
                    </div>
                    <div class="job-title mt-2">
                        <a class="#">

                            Sales & marketing
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6 mt-3">
                <div class="job-wrap">
                    <div class="job-icon">
                        <i class="fa fa-graduation-cap"></i>
                    </div>
                    <div class="job-title mt-2">
                        <a class="#">
                            Legal Job
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6 mt-3">
                <div class="job-wrap">
                    <div class="job-icon">
                        <i class="fa fa-university"></i>
                    </div>
                    <div class="job-title mt-2">
                        <a class="#">
                            Banking
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-6 mt-3">
                <div class="job-wrap">
                    <div class="job-icon">
                        <i class="fa fa-paint-brush"></i>
                    </div>
                    <div class="job-title mt-2">
                        <a class="#">
                            Design & Art
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="read-btn text-center">
            <a class="" href="#">View all categories</a>
        </div>
    </div>
</section>
<section class="featured-wrap padding">
    <div class="container">
        <div class="row justify-content-center align-items-center text-center mb-4">
            <div class="col">
                <div class="section-heading mx-auto mb-4">
                    <p>Browse Your jobs</p>
                    <h2>Featured Jobs</h2>
                </div>
            </div>
        </div>
        <div class="row justify-content-center align-items-center">
           
            @foreach (var item in Model.Jobs)
            {
                <div class="col-md-6 col-sm-6">
                    <div class="listWrpService">
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-3">
                                <div class="listImg">
                                    <img src="images/feature01.png" />
                                </div>
                            </div>
                            <div class="col-md-9 col-sm-9 col-xs-9">
                                <h3><a href="#">@item.JobTitle</a></h3>
                                <p>@item.JobPosition</p>
                                <span>@item.EmployerName</span>
                                <ul class="featureInfo">
                                    <li><i class="fa fa-map-marker" aria-hidden="true"></i>@item.EmployerLocation</li>
                                    <li><i class="fa fa-calendar" aria-hidden="true"></i>@item.UploadDate</li>
                                </ul>
                                <div class="time-btn">@item.JobType</div>
                                <div class="click-btn"><a href="/Application/Index/@item.Id">Apply Now</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
        <div class="read-btn text--center">
            <a class="" href="/Jobs/AllJobs">View all jobs</a>
        </div>
    </div>
</section>
<section class="works-wrap padding text--center">
    <div class="container">
        <div class="row justify-content-center align-items-center text-center mb-4">
            <div class="col">
                <div class="section-heading mx-auto mb-4">
                    <p>know</p>
                    <h2>How it works</h2>
                </div>
            </div>
        </div>
        <div class="row justify-content-center align-items-center works-service">
            <div class="col-md-4">
                <div class="worksIcon"><i class="fa fa-file-signature"></i></div>
                <h3>Register</h3>
                <p>Eiusmod tempor incidiunt labore velit dolore magna aliqu sed eniminim veniam quis nostrud exercition eullamco laborisaa</p>
            </div>
            <div class="col-md-4">
                <div class="worksIcon"><i class="fa fa-paper-plane"></i></div>
                <h3>Apply for Your Jobs</h3>
                <p>Eiusmod tempor incidiunt labore velit dolore magna aliqu sed eniminim veniam quis nostrud exercition eullamco laborisaa</p>
            </div>
            <div class="col-md-4">
                <div class="worksIcon"><i class="fa fa-check-square"></i></div>
                <h3>Hired Now</h3>
                <p>Eiusmod tempor incidiunt labore velit dolore magna aliqu sed eniminim veniam quis nostrud exercition eullamco laborisaa</p>
            </div>
        </div>
    </div>
</section>
<!-- End add lyrics -->
<section class="subscribe padding text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <h1 class="text-center">Get New Jobs Notification!</h1>
                <p class="mb-3">Subscribe & get all related jobs notification.</p>
                <div class="input-group">
                    <input class="form-control py-2" type="search" placeholder="Your Email Address">
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary search-btn" type="button">
                            @*<i class="fa fa-search"></i>*@
                            Subscribe
                        </button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</section>
<footer class="footer text-center">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Location</h4>
                <p class="lead mb-0">
                    1B, Olabanji Olajide Street
                    <br>Lekki Phase1
                </p>
            </div>
            <!-- Footer Social Icons -->
            <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4">Social Media Platforms</h4>
                <a class="btn btn-outline-light btn-social mx-1" href="https://www.facebook.com/idam.okechukwu">
                    <i class="fab fa-fw fa-facebook-f"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" href="https://twitter.com/idam_okechukwu">
                    <i class="fab fa-fw fa-twitter"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" href="https://www.linkedin.com/in/samuel-idam-724039140/">
                    <i class="fab fa-fw fa-linkedin-in"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" href="https://www.instagram.com/okechukwuidam/?hl=en">
                    <i class="fab fa-fw fa-instagram"></i>
                </a>
            </div>
            <!-- Footer About Text -->
            <div class="col-lg-4">
                <h4 class="text-uppercase mb-4">About Recruitment Portal</h4>
                <p class="lead mb-0">
                    Recruitment Portal is a product of Idam Okechukwu Samuel
                </p>
            </div>
        </div>
    </div>
</footer>